name: drugflow
channels:
  - pytorch
  - pyg
  - anaconda
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - appdirs=1.4.4
  - attr=2.5.2
  - attrs=25.4.0
  - biopython=1.83
  - blas=1.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - colorama=0.4.6
  - contourpy=1.3.3
  - cpython=3.11.14
  - cuda-cudart=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - docker-pycreds=0.4.0
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glew=2.2.0
  - glib=2.86.1
  - glib-tools=2.86.1
  - glm=1.0.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.2.4
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - intel-openmp=2022.0.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.6.1.9
  - libcups=2.3.3
  - libcurand=10.3.2.106
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=4.25.3
  - librdkit=2025.03.6
  - libsndfile=1.2.2
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.10
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.6.3
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - networkx=3.5
  - nspr=4.38
  - nss=3.117
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - openbabel=3.1.1
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pathtools=0.1.2
  - pcre2=10.46
  - pillow=12.0.0
  - pip=24.0
  - pixman=0.46.4
  - ply=3.11
  - pmw=2.1.1
  - prody=2.4.0
  - propcache=0.3.1
  - protobuf=4.25.3
  - psutil=7.1.3
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pycairo=1.28.0
  - pycparser=2.22
  - pyg=2.5.1
  - pymol-open-source=3.1.0
  - pyparsing=3.2.5
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.2.1
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt-main=5.15.15
  - rdkit=2025.03.6
  - readline=8.2
  - reportlab=4.4.4
  - requests=2.32.5
  - rlpycairo=0.4.0
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - sentry-sdk=2.44.0
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - sip=6.7.12
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sqlalchemy=2.0.44
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - torchmetrics=1.8.2
  - torchtriton=2.2.0
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wandb=0.16.3
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xf86vidmodeproto=2.3.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - braceexpand==0.1.7
      - dataclasses==0.6
      - dill==0.4.0
      - fcd==1.2.2
      - griddataformats==1.0.2
      - mda-xdrlib==0.2.0
      - mdanalysis==2.10.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - multiprocess==0.70.18
      - pandas==1.5.3
      - posebusters==0.3.1
      - prolif==2.0.3
      - py3dmol==2.5.3
      - pyarrow==22.0.0
      - pystow==0.7.11
      - seaborn==0.13.2
      - useful-rdkit-utils==0.65
      - webdataset==0.2.86
