name: dataloader-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - rdkit
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - pip